
services:
 ultralytic-notebook:
  image: facedetection
  ports:
   - 8888:8888
  environment:
   - JUPYTER_TOKEN=facedetection
   - WAYLAND_DISPLAY=wayland-0 
   - XDG_RUNTIME_DIR=/mnt/wslg/runtime-dir
               
  volumes:

   - DISPLAY=host.docker.internal:0
   - /run/desktop/mnt/host/wslg/.X11-unix:/tmp/.X11-unix 
   - /run/desktop/mnt/host/wslg:/mnt/wslg 
   - /run/desktop/mnt/host/wslg:/mnt/wslg  

